### ISSUE TITLE
Error main.py

### ISSUE THREAD

**Issue by Eliot4** [cyrildiagne/basnet-http#1]
File "main.py", line 54
    logging.info(f'Completed in {time.time() - start:.2f}s')
                                                          ^
SyntaxError: invalid syntax

Any ideas ?

**Comment by cyrildiagne** [comment]
Could be because of the formatted string.
Sorry forgot to mention it but, are you using Python v3.6+ ?

**Comment by Eliot4** [comment]
Thank you. I used an obsolete version of python

**Comment by cyrildiagne** [comment]
Great to hear, thanks!
