### ISSUE TITLE
Do you need reference to Resnet?

### ISSUE THREAD

**Issue by thivy** [cyrildiagne/basnet-http#10]
On the docker file is this required?
# Copy Resnet.
COPY resnet34-333f7ec4.pth /root/.torch/models/resnet34-333f7ec4.pth

**Comment by cyrildiagne** [comment]
Yes it seemed better to include in the docker image, otherwise it will be downloaded at runtime.

**Comment by thivy** [comment]
Thanks @cyrildiagne Awesome job on this man!! Loving your creative skills!!
