### ISSUE TITLE
Return image on 256 x 256

### ISSUE THREAD

**Issue by robwil1966** [cyrildiagne/basnet-http#11]
Hi,

When testing with the supplied images I can only get a 256 x 256 mask image in the result. How can I get an image with the correct aspect ratio?

Thanks in advance.

Rob
![resultgirl](https://user-images.githubusercontent.com/20024123/81690195-e0ebcb80-9452-11ea-82a2-c5460eec5093.png)

**Comment by cyrildiagne** [comment]
Hi,
That's the expected behavior.
You must resize the mask back to the input image size.

**Comment by robwil1966** [comment]
Ah, ok, thanks for finding the time to reply. Great work!

**Comment by Seb1337** [comment]
Can you explain this a bit further. If i scale it up the Quality will get worse. Is there a way to increase the Resolution itself ?
