### ISSUE TITLE
result.png is broken

### ISSUE THREAD

**Issue by mortium91** [cyrildiagne/basnet-http#12]
Hi,

I got it up and running on my localhost (Hello BASNet!) with Option 1, but when i send an image to it with for example "curl -F "data=https://www.tuinflora.com/media/catalog/product/cache/5/image/500x/9df78eab33525d08d6e5fb8d27136e95/F/D/FD19294WH_163.jpg" http://localhost:8080 -o result.png
I get an result.png that is broken. It cannot be open and seem to be corrupted.

When running the basnet_test.py in the BASnet folder however i do get correct results in the test_data map, so that seems to be working.

What could i be doing wrong?

**Comment by mortium91** [comment]
I also tried with running it with Docker. Got it up and running on http://localhost:8080/. But when sending a file i get this result, with no errors after. 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   298  100    38  100   260      1     11  0:00:38  0:00:22  0:00:16    10


But when opening the result.png file i get:
"The file “result.png” could not be opened."
"It may be damaged or use a file format that Preview doesn’t recognise."

**Comment by cyrildiagne** [comment]
Could be related to https://github.com/cyrildiagne/ar-cutpaste/issues/39#issuecomment-628956000

Could you try with Postman rather than cURL?
