### ISSUE TITLE
Images are 265x265px

### ISSUE THREAD

**Issue by Seb1337** [cyrildiagne/basnet-http#14]
Is there a way i can adjust this Size? So i get a good quality image. For example 1920x1080px so i can work with those Images in a larger Scale?

**Comment by illagrenan** [comment]
https://github.com/cyrildiagne/basnet-http#faq--troubleshooting

**Comment by Seb1337** [comment]
But what does that mean. Resize it to the input size. I don't understand how this would improve the quality of the image i took. Can you give an example.

**Comment by cyrildiagne** [comment]
BASNet returns a grayscale mask so you can keep your high resolution input image and only resize the mask.
The mask won't have more information than 256x256 but your source image will have its native resolution.

**Comment by Seb1337** [comment]
@cyrildiagne But where do i find the input image. In the Folder i only find the low res images besides the mask etc.

**Comment by cyrildiagne** [comment]
The input image is the image you send to the service.
