### ISSUE TITLE
Error: Empty reply from server

### ISSUE THREAD

**Issue by rakibtg** [cyrildiagne/basnet-http#2]
Hi, thanks for the project!

I am trying to run it using docker and i have followed the instructions provided in the readme file. Everything looks good, but i have changed the host port to 8020 due to some other local project.

When i try it using curl it looks like this:
![image](https://user-images.githubusercontent.com/5412730/81046159-8d6d0100-8ed9-11ea-9bb9-f90e4d647702.png)

Running container logs:
![image](https://user-images.githubusercontent.com/5412730/81046295-e046b880-8ed9-11ea-816c-669a414c2e21.png)

Do you have any thoughts? Thanks.

**Comment by cyrildiagne** [comment]
Hi,

Looks like the instruction in my README is wrong. The server is listening on port 80 (as defined in the docker file) so could you try mounting port 80 instead of 8080? `8020:80`

If that works, I'll fix the README.

**Comment by rakibtg** [comment]
@cyrildiagne Thanks for the quick response. Yes it does solved the issue. But however, it is still returning empty response.
![image](https://user-images.githubusercontent.com/5412730/81057289-f3fc1a00-8eed-11ea-84ce-41ef52def66a.png)

Where should i move the `resnet34-333f7ec4.pth` file? 
Thanks!

**Comment by MatiasConTilde** [comment]
> Hi,
> 
> Looks like the instruction in my README is wrong. The server is listening on port 80 (as defined in the docker file) so could you try mounting port 80 instead of 8080? `8080:80`
> 
> If that works, I'll fix the README.

It also worked for me

> Where should i move the `resnet34-333f7ec4.pth` file?

In the root of this project, the same directory where the Dockerfile is. This could also be made more clear in the README

**Comment by bheather** [comment]
Hi This looks really interesting but I also get the empty reply.  I've tried your prebuilt image and built my own with the same result.

If I browse to the http://localhost:8080 I get the "Hello BASNet!" response.  I am using one of the existing test images from BASNet.  My resnet34-333f7ec4.pth is alongside my dockerfile.  My basnet.pth is in the BASNet\saved_models\basnet_bsi folder.

docker run --rm -p 8080:80 gcr.io/cyrildiagne-ml/basnet-http       [2020-05-05 01:54:37 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-05-05 01:54:37 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2020-05-05 01:54:37 +0000] [1] [INFO] Using worker: sync
[2020-05-05 01:54:37 +0000] [8] [INFO] Booting worker with pid: 8
[2020-05-05 01:56:08 +0000] [16] [INFO] Booting worker with pid: 16
[2020-05-05 01:56:20 +0000] [1] [INFO] Handling signal: term
[2020-05-05 01:56:20 +0000] [16] [INFO] Worker exiting (pid: 16)
Loading BASNet...
[2020-05-05 01:56:20 +0000] [1] [INFO] Shutting down: Master


:/mnt/f/dev/OpenSrc/.XR/ARCutPaste/BASNet-http$ curl -F "data=@test.jpg" http://localhost:8080 -o result.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  365k    0     0  100  365k      0  41536  0:00:09  0:00:09 --:--:--     0
curl: (52) Empty reply from server

**Comment by rakibtg** [comment]
@MatiasConTilde Still it's sending an empty response. Is it working for you using Docker?

**Comment by viktorlorentz** [comment]
@rakibtg For me it worked with the prebuilt image after increasing the allocated memory in the docker desktop preferences under resources.

@cyrildiagne Nice work!

**Comment by yeahlo** [comment]
thx @viktorlorentz increase the memory solved the problem 

@cyrildiagne thank you for the code !

**Comment by amardeepsingh20** [comment]
I increased the allocated memory  in docker desktop preferences but still getting this error

> `curl: (52) Empty reply from server`

**Comment by bheather** [comment]
Yes this fixed it for me too - thanks - 6Mb worked for me

**Comment by ivoneijr** [comment]
After increase the allocated memory, I keep getting curl: (52) Empty reply from server also.

**Comment by ivoneijr** [comment]
@amardeepsingh20 did you increase only on docker desktop settings ?
Don't forget, if you increase on docker desktop settings, don't use `-m`  option on docker run command.

I got the same problems than you, here is what i did:

- increase allocation memory to 2gb on docker desktop settings (it's to much, I know, but it's just to have sure that memory is not a problem at this point)
- change default port on dockerfile `ENV PORT 3000` 
- run `docker run --rm -p 3000:3000 basnet` 

Working very well.

**Comment by buskerone** [comment]
~~ I followed @ivoneijr suggestions but I keep getting `(52) Empty reply from server`.  ~~

EDIT: This settings work great: 

<img width="504" alt="settings" src="https://user-images.githubusercontent.com/2034112/81149886-0fe2d880-8f4d-11ea-949b-e0bfacf6e422.png">

Result: 
<img width="236" alt="terminal" src="https://user-images.githubusercontent.com/2034112/81150238-93042e80-8f4d-11ea-9f77-33788811427b.png">

![1CC28EB8-EFC6-4195-AD84-24315DBAB9E3](https://user-images.githubusercontent.com/2034112/81150030-41f43a80-8f4d-11ea-9c9e-c2e7eb51cabe.JPG)

**Comment by amardeepsingh20** [comment]
I was able to get it working on my Macbook Air after increasing the worker timeout setting of gunicorn to 300 .. seems like the GPU is not getting used and it is taking upwards of 200 seconds to process one image of 800x800 pixels. :(

**Comment by cyrildiagne** [comment]
Thanks everyone for the feedback. I've fixed the `8080:80` port and added RAM requirements in the README.

@amardeepsingh20 Strange, on my macbookpro 2.8Ghz / 16 Gb of RAM I'm not getting this kind of latency. But yes, it runs a LOT faster with CUDA support. Nothing I can do here as it's the model's requirements.

There are many different issues in this thread now making it hard to track. I'm closing, but feel free to reopen if something's left out.

Cheers,
