### ISSUE TITLE
Image Permission Denied

### ISSUE THREAD

**Issue by amardeepsingh20** [cyrildiagne/basnet-http#3]
I am trying to run the image on Google Cloud Run but it seems that the permission to read the image is denied. I am getting this error in Google Cloud Run console. 

_

> Google Cloud Run Service Agent must have permission to read the image, gcr.io/cyrildiagne-ml/basnet-http. Ensure that the provided container image URL is correct and that the above account has permission to access the image. If you just enabled the Cloud Run API, the permissions might take a few minutes to propagate. Note that the image is from project [cyrildiagne-ml], which is not the same as this project [playground-amardeep]. Permission must be granted to the Google Cloud Run Service Agent from this project.

_

**Comment by cyrildiagne** [comment]
Sorry, the image wasn't correctly configured. It's public now so you should be able to pull!

EDIT: In case someone comes back here, the image has been moved to docker hub so make sure you now use: `docker.io/cyrildiagne/basnet-http`

**Comment by amardeepsingh20** [comment]
Thanks. I was able to deploy it on Cloud Run but I am getting memory limit errors. 

> Memory limit of 2048M exceeded with 2307M used. Consider increasing the memory limit
> Cloud Run does not have GPU .. is that the reason?
> 

What is the best way to deploy it on Google Cloud/AWS? If you could give some directions that would be great! Thanks

**Comment by cyrildiagne** [comment]
I've added more details about the memory requirements in the [basnet-http](https://github.com/cyrildiagne/basnet-http) repo.
But adding detailed informations on how to deploy to a cloud instance is beyond the scope of this prototype. Would make sense to have then in the basnet-http repo though!
