### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by sivakron2779** [cyrildiagne/basnet-http#4]
Thanks for sharing nice code !
But i have some error with my CUDA
when i run BASNet-http with " curl -F "data=@warning.jpg" http://192.168.1.16:1500 -o result.png "
with filename " warning.jpg " just 8 kb of size but it's have error with 
 '' RuntimeError: CUDA error: out of memory ''

my specs is  > CPU : Intel i5 - 4460
                        VGA : GTX750 TI with 2gb of memory
                        RAM : 8 Gb
How can i solve this problem , thank you ! :)   

![95930839_600316997499470_6959479639668424704_n](https://user-images.githubusercontent.com/50454836/81155009-b0b5b000-8fae-11ea-9604-ad6db7655bde.png)

**Comment by bobbybooble** [comment]
### **same here .**

**Comment by cyrildiagne** [comment]
Hi, you need a graphic card with at least 6Gb of RAM.
Since that's the model's requirements, there's nothing I can do sorry.
