### ISSUE TITLE
Get black-white image

### ISSUE THREAD

**Issue by KamMif** [cyrildiagne/basnet-http#5]
I run the project on my local machine and after processing image6 get black white img
Whats I do wrong? 
**Sample:** 
![unnamed](https://user-images.githubusercontent.com/13984868/81189161-f2e6ed80-8fbe-11ea-8f83-ed14aa490711.jpg)

**Result:**

![result](https://user-images.githubusercontent.com/13984868/81189184-fa0dfb80-8fbe-11ea-8b1e-ef66d77b06ea.png)

I newbie in ML and in its library sorry if my question is dummy^ thanks

**Comment by cyrildiagne** [comment]
Hi!

Tha looks like the expected result. This service only returns the black and white mask.
You must then apply this mask to the alpha channel of your image. For instance using `PIL.Image.composite`
