### ISSUE TITLE
Empty response to test curl

### ISSUE THREAD

**Issue by j1m-renwick** [cyrildiagne/basnet-http#8]
When I start the docker image and run a GET curl request, I get the expected "Hello BASNet!" response, but when I try the POST test request mentioned in the readme, I only get an empty response:

 ```
$ curl -F "data=@apples.jpeg" http://localhost:8080 -o result.png

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3249    0     0  100  3249      0    361  0:00:09  0:00:08  0:00:01     0
curl: (52) Empty reply from server
```

Curl seems to upload and send the image, but there is no response - if I try sending a bad request like ""data=" I get a 400 error, so it looks like the endpoint is correct and the code is being executed...just not when I send an image to be processed.  

The only thing I can think of at this point is that the processing is so extreme. that the Macbook Pro I'm running it on can't handle it before the flask request timeout is reached, but this is just a wild guess. Anything you can suggest/advise would be helpful.  Thanks :)

**Comment by cyrildiagne** [comment]
Just out of curiosity, to do the request with [Postman](https://www.postman.com/)?

**Comment by cyrildiagne** [comment]
As suggested here: https://github.com/cyrildiagne/ar-cutpaste/issues/26#issuecomment-625352279

**Comment by j1m-renwick** [comment]
same response:

![image](https://user-images.githubusercontent.com/52238993/81346736-b399c900-90b2-11ea-90a4-f38cbb06ab6a.png)

**Comment by LudovicoLucaSantucci** [comment]
I have the same problem.

> ```
>$ curl -F "data=@Lion_Afrique.jpg" http://localhost:3000 -o result.png
> % Total    % Received % Xferd  Average Speed   Time     Time       Time  Current
>                                 Dload  Upload  Total    Spent      Left   Speed
>100 1364k    0       0  100 1364k   0    118k  0:00:11  0:00:11  --:--:--     0
>curl: (52) Empty reply from server
> ```
<img width="957" alt="Screenshot 2020-05-08 at 00 15 11" src="https://user-images.githubusercontent.com/26360631/81349825-11351200-90c1-11ea-8a32-ba98aafcc04f.png">

**Comment by cyrildiagne** [comment]
Could you try increasing the RAM of Docker as mentioned here? https://github.com/cyrildiagne/ar-cutpaste/issues/26#issuecomment-625689672

**Comment by sotospez** [comment]
i have the same with mac os , i change the settings of my docker to 4 core and more ram and works fine
thanks

**Comment by LudovicoLucaSantucci** [comment]
Thanks @cyrildiagne @sotospez 
It works fine.
<img width="1325" alt="Screenshot 2020-05-08 at 14 05 28" src="https://user-images.githubusercontent.com/26360631/81404191-395e5880-9135-11ea-95ef-b125bb74d143.png">

**Comment by cyrildiagne** [comment]
Nice! @j1m-renwick can you confirm that works for you too?

**Comment by sotospez** [comment]
Works fine thanks @cyrildiagne

![11](https://user-images.githubusercontent.com/5630228/81408176-6dda1080-9145-11ea-801e-d18aae7ce3b7.jpg)
![result](https://user-images.githubusercontent.com/5630228/81408189-729ec480-9145-11ea-8ac5-22a78b3e5ba6.png)

**Comment by j1m-renwick** [comment]
@cyrildiagne yes that fixed the problem, thanks for your help :)
